[project]
name = "aws-bedrock-dev"
version = "0.1.0"
description = "Bedrock app test"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.20",
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-aws>=6.0.2,<7.0.0",
]
